Repository seantomburke/shipit.gifs, pull requests merged in 2022-04, with the labels that each got.

#37 Add a gif
  gifs.json
Labels: size/XS

#38 Upgrade tools and add GIFs
  .cache.json
  .github/workflows/npmpublish.yml
  .github/workflows/npmtestpullrequest.yml
  .github/workflows/versionbump.yml
  .gitignore
  .husky/pre-commit
  .prettierrc
  .prettierrc.json
  .travis.yml
  README.md
  add-gif.js
  cache.js
  domains.json
  gif.test.js
  gifs.json
  package.json
  test.js
  yarn.lock
Labels: size/XXL

#39 Add GIFs and fix version bump script
  gifs.json
  package.json
Labels: size/S

#40 Updating version bump github action to draft a release on merge to master
  .github/workflows/versionbump.yml
Labels: size/S
